version: "2"
services:
  web:
    container_name: redis-administration.symfony
    image: redis-administration
    ports:
      - "8000:8000"
      - "22:22"
    depends_on:
      - redis
      - mailhog
    volumes:
      - .:/opt/application
    links:
      - redis
      - mailhog

  redis:
    container_name: redis-administration.redis
    image: redis
    ports:
      - "6379:6379"

  mailhog:
    container_name: redis-administration.mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
